# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _cpgnumpy
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class cPgNumpy(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, cPgNumpy, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, cPgNumpy, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _cpgnumpy.new_cPgNumpy(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _cpgnumpy.delete_cPgNumpy
    __del__ = lambda self : None;
    def open(*args): return _cpgnumpy.cPgNumpy_open(*args)
    def execute(*args): return _cpgnumpy.cPgNumpy_execute(*args)
    def fetchall(*args): return _cpgnumpy.cPgNumpy_fetchall(*args)
    def write(*args): return _cpgnumpy.cPgNumpy_write(*args)
    def use_text(*args): return _cpgnumpy.cPgNumpy_use_text(*args)
    def set_decorators(*args): return _cpgnumpy.cPgNumpy_set_decorators(*args)
    def execwrite(*args): return _cpgnumpy.cPgNumpy_execwrite(*args)
    def set_fetch_count(*args): return _cpgnumpy.cPgNumpy_set_fetch_count(*args)
    def ntuples(*args): return _cpgnumpy.cPgNumpy_ntuples(*args)
    def nfields(*args): return _cpgnumpy.cPgNumpy_nfields(*args)
    def status(*args): return _cpgnumpy.cPgNumpy_status(*args)
    def set_field_lengths(*args): return _cpgnumpy.cPgNumpy_set_field_lengths(*args)
    def clear_field_lengths(*args): return _cpgnumpy.cPgNumpy_clear_field_lengths(*args)
    def clear(*args): return _cpgnumpy.cPgNumpy_clear(*args)
    def close(*args): return _cpgnumpy.cPgNumpy_close(*args)
cPgNumpy_swigregister = _cpgnumpy.cPgNumpy_swigregister
cPgNumpy_swigregister(cPgNumpy)



